# Generated by Django 5.1.5 on 2025-02-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('tipo_unidade', models.CharField(max_length=50, verbose_name='Tipo de Unidade')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidade')),
                ('start_process', models.DateField(blank=True, null=True, verbose_name='Início do Processo')),
                ('candidato', models.CharField(max_length=100, verbose_name='Candidato')),
                ('contato_telefone', models.CharField(max_length=20, verbose_name='Contato Telefone')),
                ('email_candidato', models.EmailField(max_length=254, verbose_name='E-mail do Candidato')),
                ('primeira_meeting_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='1ª Meeting')),
                ('direx_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='Direx')),
                ('planej_rotas_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='Planej. (Rotas)')),
                ('cnpj_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='CNPJ')),
                ('contrato_social_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='Contrato Social')),
                ('im_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='I.M.')),
                ('ie_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='I.E.')),
                ('rg_socio_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='RG (Sócio)')),
                ('cpf_socio_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='CPF (Sócio)')),
                ('comprovante_residencia_socio_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='Comprovante de Residência (Sócio)')),
                ('rg_fiador_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='RG (Fiador)')),
                ('cpf_fiador_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='CPF (Fiador)')),
                ('comprovante_residencia_fiador_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='Comprovante de Residência (Fiador)')),
                ('escritura_imovel_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='Escritura Imóvel')),
                ('dados_bancario_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='Dados Bancários')),
                ('imovel_franquia_analise_status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='nao', max_length=10, verbose_name='Imóvel Franquia (Análise)')),
                ('email_cnaes_data', models.DateField(blank=True, null=True, verbose_name="E-mail CNAE's")),
                ('mae_data', models.DateField(blank=True, null=True, verbose_name='MAE (Manual Assinatura Eletrônica)')),
                ('pedido_analise_fin_data', models.DateField(blank=True, null=True, verbose_name='Pedido Análise Fin.')),
                ('confirma_analise_fin_data', models.DateField(blank=True, null=True, verbose_name='Confirmação Análise Fin.')),
                ('email_equipamentos_data', models.DateField(blank=True, null=True, verbose_name='E-mail Equipamentos')),
                ('mkt_projeto_arquitetura_data', models.DateField(blank=True, null=True, verbose_name='MKT (Projeto Arquitetura)')),
                ('envio_paf_data', models.DateField(blank=True, null=True, verbose_name='Envio PAF')),
                ('assinatura_paf_data', models.DateField(blank=True, null=True, verbose_name='Assinatura PAF')),
                ('envio_ccf_data', models.DateField(blank=True, null=True, verbose_name='Envio CCF')),
                ('assinatura_ccf_data', models.DateField(blank=True, null=True, verbose_name='Assinatura CCF')),
                ('envio_cof_data', models.DateField(blank=True, null=True, verbose_name='Envio COF')),
                ('assinatura_cof_data', models.DateField(blank=True, null=True, verbose_name='Assinatura COF')),
                ('subir_projuris_data', models.DateField(blank=True, null=True, verbose_name='Subir para Projuris')),
                ('assinado_projuris_data', models.DateField(blank=True, null=True, verbose_name='Assinado Projuris')),
                ('solicitacao_senha_franchising_data', models.DateField(blank=True, null=True, verbose_name='Solicitação Senha Franchising')),
                ('validacao_helpdesk_data', models.DateField(blank=True, null=True, verbose_name='Validação Helpdesk')),
                ('inclusao_planilha_data', models.DateField(blank=True, null=True, verbose_name='Inclusão Planilha')),
                ('central_lat_long_data', models.DateField(blank=True, null=True, verbose_name='(Central) Lat e Long')),
                ('pedido_ativacao_fin_data', models.DateField(blank=True, null=True, verbose_name='Pedido Ativação Fin.')),
                ('confirma_ativacao_fin_data', models.DateField(blank=True, null=True, verbose_name='Confirmação Ativação Fin.')),
                ('pgto_taxa_adesao', models.BooleanField(default=False, verbose_name='Pgto Taxa Adesão')),
                ('segunda_meeting_update', models.BooleanField(default=False, verbose_name='2ª Meeting/Update')),
                ('treinamento', models.BooleanField(default=False, verbose_name='Treinamento')),
                ('inclusao_planilha', models.BooleanField(default=False, verbose_name='Inclusão Planilha')),
                ('email_oficial', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Oficial')),
                ('codigo_etiqueta_teca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Etiqueta Teca')),
                ('ponto_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ponto Número')),
                ('numero_contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Contrato')),
                ('infow_week', models.CharField(blank=True, max_length=50, null=True, verbose_name='InfoW (Week)')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/', verbose_name='Anexo')),
                ('status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('cobrado', 'Cobrado'), ('pendente', 'Pendente'), ('ativa', 'Ativa')], default='pendente', max_length=10, verbose_name='Status')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
