# Generated by Django 5.1.5 on 2025-02-03 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='unidade',
            name='usuarios',
            field=models.ManyToManyField(related_name='unidades', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Associados'),
        ),
    ]
